// Generated by Wrangler on Tue Dec 31 2024 17:38:13 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
